In [49]:
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 5

print (gen_vander_matrix(inputvector,no_col_opmat,increasing=True))
print ("==========")
print (gen_vander_matrix(inputvector,no_col_opmat,increasing=False))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [43]:
import numpy as np
narr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win=3
#j=0
no_loop= len(narr) - win +1
print (no_loop)
mvavg=[]
def movingave()
for i in range(0,no_loop):
    summ=0
    start = i
    end = i + win
    #print (start,end)
    for k in range(start,end):
        #print (narr[k])
        summ = narr[k] + summ
    #print('sum is', summ)
        
    mvavg.append(summ / win)
    #print (mvavg[i])
print (mvavg)   

11
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
